#!/bin/bash

export DISPLAY=:1
SESSNAME="qemucon"
SESSPATH="/dos/runimages/$SESSNAME"

set -e
set -x

if [ ! -d "$SESSPATH" ]; then 
  mksessimg /dos/baseimages/freedos-c-net.qcow2.gz "$SESSNAME"
fi

waitfordaemon vncserver true
waitfordaemon smbd true
waitfordaemon nmbd true

set +e
qemu-system-i386 -localtime \
   -m 32M \
   "$SESSPATH/c.qcow2" -boot c \
   -hdb "fat:$SESSPATH/drive_d" \
   -net nic,model=pcnet -net user \
   -name "$SESSNAME" -vnc :2
   -chardev socket,id=com1,host=localhost,port=7000 -device isa-serial,chardev=com1
RETCODE="$?"
exit "$RETCODE"

